/* Opciones B y equipo alternativo */
(()=>{
const KEY='rutinaEntreno.optionB.v1';
const PROFILE='lucas-rutina';
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const weekKey=()=>{const d=new Date(),q=(d.getDay()+6)%7,m=new Date(d.getFullYear(),d.getMonth(),d.getDate()-q);return `${m.getFullYear()}-${String(m.getMonth()+1).padStart(2,'0')}-${String(m.getDate()).padStart(2,'0')}`};
const read=()=>{try{const x=JSON.parse(localStorage.getItem(KEY)||'null');return x&&x.weekKey===weekKey()?x:{weekKey:weekKey(),choices:{},updatedAt:0}}catch{return{weekKey:weekKey(),choices:{},updatedAt:0}}};
const write=s=>{s.weekKey=weekKey();s.updatedAt=Date.now();localStorage.setItem(KEY,JSON.stringify(s));syncCloud(s)};
const alt={
'bicicleta suave':{name:'Marcha suave en trampolín',equipment:'Trampolín',works:'Cardio suave · circulación · coordinación',how:'Marchá sin despegar ambos pies a la vez. Tronco alto, pasos cortos y ritmo cómodo.',note:'Solo si el trampolín admite tu peso. Sin rebotes altos; si el gemelo molesta, usá caminata o bici.'},
'sentadilla goblet':{name:'Sentarse y pararse de una silla',equipment:'Silla firme + mancuerna opcional',works:'Cuádriceps · glúteos · core',how:'Sentate atrás tocando la silla y volvé a pararte empujando el piso. Rodillas siguiendo la línea de los pies.',note:'Empezá sin peso; después sostené 3-5 kg al pecho.'},
'remo a 1 brazo':{name:'Remo con banda anclada a puerta',equipment:'Banda + anclaje de puerta',works:'Dorsales · romboides · bíceps',how:'Anclá a la altura del ombligo, agarrá la banda y llevá los codos hacia atrás sin encoger hombros.',note:'Probá el anclaje con poca tensión antes de empezar.'},
'flexiones de brazos':{name:'Press de pecho con banda en puerta',equipment:'Banda + anclaje de puerta',works:'Pecho · tríceps · hombro anterior',how:'Anclaje detrás tuyo a altura del pecho. Empujá las manos al frente y volvé lento.',note:'Alternativa más amable que la flexión si todavía cuesta mover tu peso corporal.'},
'curl de biceps':{name:'Curl de bíceps con banda',equipment:'Banda + anclaje bajo de puerta',works:'Bíceps · antebrazo',how:'Anclaje bajo. Codos pegados al cuerpo; doblá los codos sin mover hombros y bajá lento.',note:'También podés pisar la banda si no querés usar la puerta.'},
'curl martillo':{name:'Curl martillo con banda',equipment:'Banda bajo los pies',works:'Bíceps · braquial · antebrazo',how:'Pisá el centro de la banda y agarrá con palmas enfrentadas. Subí sin balancear el torso.',note:'Usá una tensión que permita terminar con técnica limpia.'},
'triceps por encima de la cabeza':{name:'Jalón de tríceps con banda',equipment:'Banda + anclaje alto de puerta',works:'Tríceps',how:'Anclá arriba. Codos pegados al cuerpo; empujá hacia abajo hasta estirar y regresá lento.',note:'Suele ser más cómodo para hombros que la variante por encima de la cabeza.'},
'triceps con banda':{name:'Patada de tríceps apoyado en silla',equipment:'Silla firme + mancuerna 3-5 kg',works:'Tríceps',how:'Una mano sobre la silla, torso inclinado y codo pegado al cuerpo. Estirá el antebrazo hacia atrás.',note:'No muevas el hombro; solo el codo.'},
'elevaciones laterales':{name:'Elevación lateral con banda',equipment:'Banda bajo los pies',works:'Deltoide lateral · estabilidad escapular',how:'Pisá la banda y elevá brazos hasta aproximadamente altura de hombros, sin impulso.',note:'Menos tensión si sentís que necesitás balancearte.'},
'press de hombros':{name:'Press sentado en silla',equipment:'Silla firme + mancuernas 3-5 kg',works:'Hombros · tríceps · core',how:'Sentate erguido con respaldo estable. Empujá las mancuernas arriba sin arquear la espalda.',note:'La silla te ayuda a controlar la postura.'},
'dead bug':{name:'Dead bug con talones sobre silla',equipment:'Silla firme',works:'Abdomen profundo · control lumbar',how:'Boca arriba, talones apoyados en la silla y rodillas a 90°. Despegá un talón a la vez manteniendo la zona lumbar estable.',note:'Versión más fácil para aprender el control del core.'},
'plancha':{name:'Plancha inclinada en silla',equipment:'Silla muy firme o mesa',works:'Core · hombros · abdomen',how:'Apoyá manos en una superficie estable, caminá pies hacia atrás y mantené cuerpo recto.',note:'Cuanto más alta la superficie, más fácil.'},
'plancha lateral':{name:'Press Pallof con banda',equipment:'Banda + anclaje de puerta a pecho',works:'Oblicuos · core antirotación · glúteos',how:'Parate de costado al anclaje, sostené la banda al pecho y extendé brazos sin dejar que el torso rote.',note:'Excelente opción si la plancha lateral molesta hombro o resulta difícil.'},
'elevacion de talones, rodilla estirada':{name:'Gemelos con apoyo en silla',equipment:'Silla firme',works:'Gastrocnemio · tobillo',how:'Sujetate de la silla, subí ambos talones lento, pausá arriba y bajá todavía más lento.',note:'La silla da equilibrio; no rebotes.'},
'elevacion bilateral de talones':{name:'Gemelos con apoyo en silla',equipment:'Silla firme',works:'Gemelos · sóleo · tobillo',how:'Sujetate suavemente, elevá talones y bajá controlado. Sin buscar fatiga máxima.',note:'Si aparece tirón o pinchazo, detenelo.'},
'elevacion de talones con rodillas semiflexionadas':{name:'Gemelo sentado / sóleo',equipment:'Silla + mancuerna opcional',works:'Sóleo · gemelo profundo',how:'Sentado con pies apoyados, elevá talones manteniendo rodillas flexionadas. Podés apoyar una mancuerna sobre los muslos.',note:'Empezá sin peso y progresá lentamente.'},
'elevacion de punta del pie contra pared':{name:'Puntas de pie sentado',equipment:'Silla',works:'Tibial anterior · tobillo',how:'Sentate con talones apoyados y levantá las puntas de los pies lo más alto posible.',note:'Muy controlado; no hace falta carga al principio.'},
'peso muerto rumano':{name:'Bisagra de cadera hacia silla',equipment:'Silla + mancuerna opcional',works:'Isquios · glúteos · espalda baja',how:'Poné la silla detrás. Llevá la cola hacia atrás hasta tocarla suavemente y volvé apretando glúteos.',note:'Sirve para aprender la bisagra sin redondear la espalda.'},
'puente de gluteos':{name:'Extensión de cadera con banda en puerta',equipment:'Banda + anclaje bajo de puerta',works:'Glúteos · isquios',how:'Anclaje bajo detrás tuyo, banda alrededor de la pelvis si es apta para eso. Extendé cadera y apretá glúteos.',note:'Si el montaje no es seguro, quedate con el puente en el piso.'},
'intervalos en bicicleta':{name:'Intervalos de marcha rápida en trampolín',equipment:'Trampolín',works:'Cardio · coordinación · bajo impacto',how:'45 s de marcha rápida con brazos activos + 75 s de marcha muy suave. Repetí igual que en la bici.',note:'Sin saltos altos. Solo si el trampolín soporta tu peso y los gemelos están sin dolor.'},
'remo con banda':{name:'Remo con mancuerna apoyado en silla',equipment:'Silla firme + mancuerna 5-10 kg',works:'Dorsales · espalda media · bíceps',how:'Apoyá una mano en la silla y llevá la mancuerna hacia la cadera manteniendo espalda neutra.',note:'No gires el torso.'},
'caminata lateral con banda':{name:'Abducción de cadera con silla',equipment:'Silla firme',works:'Glúteo medio · estabilidad de cadera',how:'Sujetate de la silla y separá una pierna hacia el costado sin inclinar el torso.',note:'Movimiento corto y controlado.'},
'movilidad de tobillos y cadera':{name:'Movilidad asistida con silla',equipment:'Silla',works:'Tobillo · cadera · equilibrio',how:'Sujetate de la silla para hacer balanceos suaves de cadera y llevar la rodilla hacia delante sobre el pie sin levantar el talón.',note:'Sin rebotes ni dolor.'},
'caminar/trotar progresivo':{name:'Marcha progresiva en trampolín',equipment:'Trampolín',works:'Cardio · piernas · coordinación',how:'Empezá caminando en el lugar y aumentá la cadencia gradualmente sin saltar.',note:'Si el gemelo está cargado, hacelo en el piso o bici suave.'},
'movilidad dinamica':{name:'Movilidad dinámica con apoyo',equipment:'Silla',works:'Cadera · tobillos · isquios · aductores',how:'Sujetate de una silla y hacé balanceos de pierna cortos, círculos de cadera y tobillo de forma controlada.',note:'Nada de estiramientos bruscos.'},
'desplazamientos laterales':{name:'Pasos laterales junto a una silla',equipment:'Silla o mesada',works:'Glúteos · aductores · coordinación',how:'Pasos cortos de lado, rodillas suaves y torso estable. Usá la silla solo como referencia/apoyo.',note:'Sin cruzar pies ni hacer saltos.'},
'aceleraciones progresivas':{name:'Marcha rápida por bloques',equipment:'Trampolín o piso',works:'Cardio · coordinación · piernas',how:'15-20 s de marcha muy rápida y controlada + 40-60 s suave. Aumentá velocidad de brazos antes que impacto.',note:'No reemplaza un sprint cuando estés sano; es una opción de menor impacto.'},
'partido':{name:'Sesión cardio sin partido',equipment:'Bici o trampolín',works:'Cardio · piernas · resistencia',how:'5 min suave + 10 bloques de 1 min moderado/fuerte y 1 min suave + 5-10 min suave.',note:'Usá trampolín solo con marcha, no saltos, si los gemelos están sensibles.'},
'caminata suave':{name:'Marcha muy suave en trampolín',equipment:'Trampolín',works:'Recuperación cardiovascular · circulación',how:'Marchá despacio 5-10 min, respirando cómodo y sin rebote alto.',note:'Si hay molestia de gemelo, preferí caminar en piso firme.'},
'bicicleta muy suave':{name:'Marcha muy suave en trampolín',equipment:'Trampolín',works:'Recuperación · circulación',how:'Marchá despacio, sin saltar y con apoyo completo del pie.',note:'La recuperación debe sentirse muy fácil.'},
'bicicleta zona suave':{name:'Marcha continua en trampolín',equipment:'Trampolín',works:'Cardio aeróbico · coordinación',how:'30-45 min de marcha continua a ritmo donde puedas hablar en frases.',note:'Solo si el fabricante admite al menos tu peso actual; sin rebotes altos.'}
};
function lookup(name){return alt[norm(name)]||{name:'Versión asistida con silla o banda',equipment:'Silla firme / banda',works:'Mismos grupos musculares',how:'Reducí carga y rango de movimiento, usando una silla estable como apoyo o una banda con menor tensión.',note:'Priorizá control y cero dolor agudo.'}}
function choiceId(name){return `${selectedDay}|${name}`}
function isSelected(name){return !!read().choices[choiceId(name)]}
function toggleChoice(name){const s=read(),id=choiceId(name);s.choices[id]=!s.choices[id];write(s);decorate();if(typeof toast==='function')toast(s.choices[id]?'Opción B elegida para hoy':'Volviste a la opción principal')}
async function syncCloud(state){try{if(window.RutinaFirebase&&RutinaFirebase.isReady&&RutinaFirebase.isReady())await RutinaFirebase.syncProfile({optionBState:state,optionBUpdatedAt:state.updatedAt})}catch(e){console.warn('optionB sync',e)}}
async function hydrateCloud(){for(let i=0;i<20;i++){try{if(window.firebase&&firebase.apps&&firebase.apps.length){const db=firebase.firestore(),doc=await db.collection('rutinaEntreno').doc(PROFILE).get();if(doc.exists){const d=doc.data(),cloud=d.optionBState,local=read();if(cloud&&cloud.weekKey===weekKey()&&Number(d.optionBUpdatedAt||cloud.updatedAt||0)>Number(local.updatedAt||0)){localStorage.setItem(KEY,JSON.stringify(cloud));decorate()}}return}}catch(e){console.warn('optionB hydrate',e);return}await new Promise(r=>setTimeout(r,250))}}
function inventory(){if(document.getElementById('equipmentInventory'))return;const anchor=document.getElementById('customActiveBanner')||document.querySelector('.summary-card');if(!anchor)return;const el=document.createElement('div');el.id='equipmentInventory';el.className='equipment-inventory';el.innerHTML='<div class="equipment-title"><span>Tu equipo contemplado</span><small>opciones A y B</small></div><div class="equipment-chips"><span>Bandas + puerta</span><span>Pesas 3/5/10 kg</span><span>Silla firme</span><span>Bici</span><span>Cinta</span><span>Trampolín</span></div><div class="equipment-safety"><b>Bandas:</b> anclaje específico, puerta cerrada/trabada y prueba suave antes de tirar fuerte. <b>Trampolín:</b> usalo solo si el fabricante admite tu peso actual; por ahora priorizá marcha y rebote mínimo.</div>';anchor.insertAdjacentElement('afterend',el)}
function decorate(){inventory();document.querySelectorAll('#exerciseList .exercise').forEach(card=>{const title=card.querySelector('.exercise-name');if(!title)return;const name=title.textContent.trim();const a=lookup(name);card.querySelector('.option-b-wrap')?.remove();const selected=isSelected(name);card.classList.toggle('option-b-active',selected);const w=document.createElement('div');w.className='option-b-wrap';w.innerHTML=`<button class="option-b-toggle" type="button"><span>Opción B</span><small>${escapeHtml(a.name)}</small><b>${selected?'ACTIVA':'VER'}</b></button><div class="option-b-panel"><div class="option-b-name">${escapeHtml(a.name)}</div><div class="option-b-meta"><span>${escapeHtml(a.equipment)}</span><span>${escapeHtml(a.works)}</span></div><p>${escapeHtml(a.how)}</p><div class="option-b-note">${escapeHtml(a.note)}</div><button class="option-b-use" type="button">${selected?'Usar opción principal':'Usar esta opción B'}</button></div>`;const btn=w.querySelector('.option-b-toggle'),panel=w.querySelector('.option-b-panel');btn.onclick=()=>{panel.classList.toggle('open');btn.classList.toggle('open')};w.querySelector('.option-b-use').onclick=()=>toggleChoice(name);card.querySelector('.exercise-body').appendChild(w)})}
const oldRender=renderDay;renderDay=function(...args){const r=oldRender.apply(this,args);setTimeout(decorate,0);return r};
const oldTutorial=openTutorial;openTutorial=function(name){const r=oldTutorial(name);setTimeout(()=>{const root=document.getElementById('tutorialContent');if(!root)return;root.querySelector('.tutorial-option-b')?.remove();const a=lookup(name),b=document.createElement('div');b.className='tutorial-block tutorial-option-b';b.innerHTML=`<h3>🔁 Opción B</h3><p><b>${escapeHtml(a.name)}</b><br>${escapeHtml(a.how)}<br><small>${escapeHtml(a.equipment)} · ${escapeHtml(a.note)}</small></p>`;root.appendChild(b)},0);return r};
window.RutinaAlternativas={lookup,toggleChoice,decorate};
setTimeout(()=>{decorate();hydrateCloud()},100);
})();